version: "3.3"
services:
  nginx: 
      image: nginx:alpine
      restart: always
      container_name: tfm-nginx
      deploy:
        resources:
            limits:
              memory: 512M
            reservations:
              memory: 128M
      networks:
        - tfm-network
      
      ports: 
        - "80:80"
        - "443:443"
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/log/nginx/:/var/log/nginx/
      depends_on:
        - tfm-backend

  tfm-backend:
    # build: .
    restart: always
    image: franmejim/tfm-backend
    expose: [ 9000 ]
    container_name: tfm-backend
    deploy:
        resources:
            limits:
              memory: 2G
            reservations:
              memory: 128M

    networks:
      - tfm-network

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./public:/usr/src/app/public
      - /var/log/server:/usr/src/app/logs/:rw
      - /var/log/server:/home/node/logs/:rw
      # - /var/log/server:/var/log/server:rw
      
    depends_on: [ tfm-database ]

  tfm-database:
    restart: always
    expose: [ 5432 ]
    # image: postgres:14.3-alpine
    build: 
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: tfm-database
    deploy:
        resources:
            limits:
              memory: 1G
            reservations:
              memory: 128M
    env_file:
      - .env.docker
    networks:
      - tfm-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      # - ./scripts/:/etc/letsencrypt/renewal-hooks/deploy/

networks:
  tfm-network:
    name: tfm-network
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/28
          gateway: 192.168.80.1