version: "3.3"
services:
  nginx: 
      image: nginx:alpine
      restart: always
      container_name: tfm-nginx
      deploy:
        resources:
            limits:
              memory: 512M
            reservations:
              memory: 128M
      ports: 
        - "80:80"
        - "443:443"
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/log/nginx/:/var/log/nginx/
      depends_on:
        - tfm-backend
        # - tfm-database

  tfm-backend:
    # build: .
    restart: always
    image: franmejim/tfm-backend
    expose: [ 9000 ]
    container_name: tfm-backend
    deploy:
        resources:
            limits:
              memory: 2G
            reservations:
              memory: 128M
    volumes:
      - ./public:/usr/src/app/public
      - ./logs/:/var/log
      
    depends_on: [ tfm-database ]

  tfm-database:
    restart: always
    ports: ["8000:5432"]
    expose: [ 5432 ]
    image: postgres:14.2-alpine
    container_name: tfm-database
    deploy:
        resources:
            limits:
              memory: 1G
            reservations:
              memory: 128M
    env_file:
      - .env.docker
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/:rw
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh