FROM postgres:14.3-alpine

WORKDIR /etc/letsencrypt/renewal-hooks/deploy

COPY ./scripts/postgres-deploy.sh .

RUN chmod 0177 postgres-deploy.sh

# WORKDIR /var/lib/postgresql/data
# USER postgres
# COPY pg_hba.conf /var/lib/postgresql/data/pgdata

# COPY postgresql.conf .
# USER root
# VOLUME /var/lib/postgresql/data/pgdata
WORKDIR /

# RUN chown -R root:posgres /var/lib/postgresql/
# RUN chmod -R 777  /var/lib/postgresql/

CMD [ "postgres" ]