FROM postgres:14.3-alpine

RUN chown postgres:postgres /var/lib/postgresql/data

USER postgres

CMD [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf" ] 