FROM postgres:14.3-alpine

WORKDIR /etc/letsencrypt/renewal-hooks/deploy

COPY ./scripts/postgres-deploy.sh .

RUN chmod 0177 postgres-deploy.sh

# WORKDIR /var/lib/postgresql/data/pgdata

# COPY pg_hba.conf .
# COPY postgresql.conf .

WORKDIR /

CMD [ "postgres" ]