#!/bin/bash
set -e

# echo "pre" > /etc/letsencrypt/renewal-hooks/deploy/postgres-deploy.sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-`EOSQL`
    CREATE USER $PG_SERVER_USER WITH ENCRYPTED PASSWORD '$PG_SERVER_PWD';
    CREATE DATABASE "$PG_SERVER_DB";
    GRANT CONNECT, CREATE ON DATABASE "$PG_SERVER_DB" TO $PG_SERVER_USER;
    \connect "$PG_SERVER_DB"
    CREATE SCHEMA IF NOT EXISTS "$PG_SERVER_DB_SCHEMA";
    GRANT USAGE ON SCHEMA "$PG_SERVER_DB_SCHEMA" TO $PG_SERVER_USER;
    GRANT SELECT, DELETE, UPDATE, INSERT ON ALL TABLES IN SCHEMA "$PG_SERVER_DB_SCHEMA" TO $PG_SERVER_USER;
`EOSQL`   