
-- 
-- Create user and database
-- 
CREATE USER $PG_SERVER_USER WITH ENCRYPTED PASSWORD "$PG_SERVER_PWD";
CREATE DATABASE $PG_SERVER_DB;
GRANT CONNECT, CREATE ON DATABASE $PG_SERVER_DB TO "$PG_SERVER_USER";

-- 
-- Connect to database
-- 
\connect $PG_SERVER_DB

-- 
-- Create schema and grant privileges
-- 
CREATE SCHEMA IF NOT EXISTS $PG_SERVER_DB_SCHEMA;
GRANT SELECT, DELETE, UPDATE, INSERT ON ALL TABLES IN SCHEMA "$PG_SERVER_DB_SCHEMA" TO "$PG_SERVER_USER";
